name: adit_quiz
version: 1.0.0+1
publish_to: none
description: A new Flutter project for quiz app.
environment: 
  sdk: '>=3.1.0 <4.0.0'

dependencies: 
  flutter: 
    sdk: flutter
  
  # ui
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  velocity_x: ^4.1.1
  simple_circular_progress_bar: ^1.0.2

  # firebase
  firebase_core: ^2.22.0
  firebase_analytics: ^10.7.0
  cloud_firestore: ^4.13.1
  firebase_crashlytics: ^3.4.4

  # misc
  share_plus: ^7.2.1
  
dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

get_cli: 
  sub_folder: false

